profile:
  name: Arin
  alias: 灰
  tagline: 君に出会い、夢に翔ける
  avatar: /assets/images/avatar/profile.jpg
  hero: /assets/images/hero/main.jpg
links:
  - label: GitHub
    icon: github
    url: https://github.com/arin3000
  - label: Bilibili
    icon: bilibili
    url: https://space.bilibili.com/421015626
  - label: Pixiv
    icon: pixiv
    url: https://www.pixiv.net/users/75350571
  - label: Mail
    icon: mail
    url: mailto:avalon2967@gmail.com
